### PR TITLE
chore: update go-kong to v0.57.1

### PR DESCRIPTION
**Pull request by Prashansa-K**
The new go-kong version ensures that shorthand_fields are filled with defaults or nested config values. If the shorthand_fields are set, the nested fields are backfilled to keep both in sync. This ensures that deck diff or deck sync commands do not show unnecessary updates in plugin configs.

Fix for [#1251](https://github.com/Kong/deck/issues/1251) from deck issues.

### CODE REVIEW

**Review by pmalek — APPROVED** [review]

**Comment by pmalek** [comment]
It looks like test failures needs addressing https://github.com/Kong/go-database-reconciler/actions/runs/10252010211/job/28361391166?pr=122

**Comment by Prashansa-K** [comment]
> It looks like test failures needs addressing https://github.com/Kong/go-database-reconciler/actions/runs/10252010211/job/28361391166?pr=122

Fixed the test. `rbac_role_get` test was erroring out.
Main issue was a missing name field due to which rbac_role wasn't getting added. Not sure how it was passing earlier. We had a `//nolint gosec` comment beside the test runner. Could this be causing a skip?

There's a rbac_role add test just above the changed test that shows that without a name, any addition would error out.
https://github.com/Kong/go-database-reconciler/blob/main/pkg/state/rbac_role_test.go#L36

cc: @GGabriele

**Review by pmalek — DISMISSED** [review]

**Comment by pmalek** [comment]
> We had a `//nolint gosec` comment beside the test runner. Could this be causing a skip?

That should only affect the linter, not whether the tests were skipped 🤔 

The actual issue that this `nolint` was trying to cover up was https://go.dev/blog/loopvar-preview, which got "fixed" in 1.22. So this directive is not needed anymore.

**Review by pmalek — DISMISSED** [review]

**Review by pmalek — APPROVED** [review]

**Comment by Prashansa-K** [comment]
This PR was closed as some more changes may be needed in go-kong for properly addressing the issue of deprecated schema fields logic and ensuring that gateway 3.7.x and 3.8.x related changes don't conflict.
More info on this slack thread: https://kongstrong.slack.com/archives/C07AQH7SAF8/p1722589141558609

**Pull request closed without merging**
